# Generated by Django 3.2.7 on 2021-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=200)),
                ('cioc', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('callingCodes', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('population', models.CharField(max_length=100, null=True)),
                ('timezone', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
